### ISSUE TITLE
这个itx小板怎么能同时插显卡和网卡？

### ISSUE THREAD

**Issue by tjcsr** [Johnny-Liang/Asrock-B660m-ITX-AC-OC-EFI#2]
显卡：AMD RX6600XT 8GB GDDR6
网卡：BCM94360CD 拆机免驱网卡

还有有具体的安装教程吗？

**Comment by Johnny-Liang** [comment]
网卡是买的拆机卡，另外需要苹果转NGFF转接卡。替换掉原主板上的无线网卡。就是要对原来的无线网卡的外壳做一下改造，钳子掰一下就可以。
